In [1]:
from google.colab import files
import pandas as pd

uploaded = files.upload()

df = pd.read_csv("Countries.csv")
print(df.head())

Saving Countries.csv to Countries.csv
       country                             country_long        currency  \
0  Afghanistan             Islamic State of Afghanistan  Afghan afghani
1      Albania                      Republic of Albania    Albanian lek
2      Algeria  People's Democratic Republic of Algeria  Algerian dinar
3      Andorra                  Principality of Andorra            Euro
4       Angola              People's Republic of Angola  Angolan kwanza

       capital_city           region continent   demonym  latitude  longitude  \
0             Kabul    Southern Asia      Asia    Afghan      33.0       65.0
1            Tirana  Southern Europe    Europe  Albanian      41.0       20.0
2           Algiers  Northern Africa    Africa  Algerian      28.0        3.0
3  Andorra la Vella  Southern Europe    Europe  Andorran      42.5        1.5
4            Luanda    Middle Africa    Africa   Angolan     -12.5       18.5

   agricultural_land  ...  population  women_parliament_seats_pct  \
0           383560.0  ...    41128771                    27.01610
1            11655.5  ...     2775634                    35.71430
2           413588.0  ...    44903225                     8.10811
3              187.2  ...       79824                    46.42860
4           569525.0  ...    35588987                    33.63640

   rural_population  urban_population  press  democracy_score  democracy_type  \
0          30181937          10946834   2.14             2.97   Authoritarian
1           1004807           1770827   2.62             5.98   Hybrid regime
2          11328186          33575039   1.71             3.50   Authoritarian
3              9730             70094   3.17             0.00         Unknown
4          11359649          24229338   2.24             3.62   Authoritarian

   median_age      political_leader               title
0        12.9          Ashraf Ghani           President
1        33.7              Edi Rama      Prime Minister
2        24.0  Abdelmadjid Tebboune           President
3        38.9   Xavier Espot Zamora  Head of Government
4        12.4         João Lourenço           President

[5 rows x 64 columns]

In [2]:
print(df.shape)
print(df.info)

(194, 64)
<bound method DataFrame.info of                 country                             country_long  \
0           Afghanistan             Islamic State of Afghanistan
1               Albania                      Republic of Albania
2               Algeria  People's Democratic Republic of Algeria
3               Andorra                  Principality of Andorra
4                Angola              People's Republic of Angola
..                  ...                                      ...
189             Vietnam            Socialist Republic of Vietnam
190  West Bank and Gaza                       West Bank and Gaza
191               Yemen                        Republic of Yemen
192              Zambia                       Republic of Zambia
193            Zimbabwe                     Republic of Zimbabwe

               currency      capital_city              region continent  \
0        Afghan afghani             Kabul       Southern Asia      Asia
1          Albanian lek            Tirana     Southern Europe    Europe
2        Algerian dinar           Algiers     Northern Africa    Africa
3                  Euro  Andorra la Vella     Southern Europe    Europe
4        Angolan kwanza            Luanda       Middle Africa    Africa
..                  ...               ...                 ...       ...
189     Vietnamese dong             Hanoi  South-Eastern Asia      Asia
190  Israeli new shekel          Ramallah        Western Asia      Asia
191         Yemeni rial            Sana'a        Western Asia      Asia
192  New Zambian kwacha            Lusaka      Eastern Africa    Africa
193         U.S. dollar            Harare      Eastern Africa    Africa

         demonym   latitude   longitude  agricultural_land  ...  population  \
0         Afghan  33.000000   65.000000           383560.0  ...    41128771
1       Albanian  41.000000   20.000000            11655.5  ...     2775634
2       Algerian  28.000000    3.000000           413588.0  ...    44903225
3       Andorran  42.500000    1.500000              187.2  ...       79824
4        Angolan -12.500000   18.500000           569525.0  ...    35588987
..           ...        ...         ...                ...  ...         ...
189   Vietnamese  16.166667  107.833333           123600.0  ...    98186856
190  Palestinian  31.900000   35.200000             4449.0  ...     5043612
191       Yemeni  15.000000   48.000000           234520.0  ...    33696614
192      Zambian -15.000000   30.000000           238360.0  ...    20017675
193   Zimbabwean -20.000000   30.000000           162000.0  ...    16320537

     women_parliament_seats_pct  rural_population  urban_population  press  \
0                      27.01610          30181937          10946834   2.14
1                      35.71430           1004807           1770827   2.62
2                       8.10811          11328186          33575039   1.71
3                      46.42860              9730             70094   3.17
4                      33.63640          11359649          24229338   2.24
..                          ...               ...               ...    ...
189                    30.26050          60123739          38063117   1.04
190                         NaN           1145354           3898258   1.75
191                     0.00000          20491585          13205029   1.27
192                    15.06020          10857387           9160288   2.15
193                    30.56600          11033499           5287038   1.85

     democracy_score  democracy_type  median_age       political_leader  \
0               2.97   Authoritarian        12.9           Ashraf Ghani
1               5.98   Hybrid regime        33.7               Edi Rama
2               3.50   Authoritarian        24.0   Abdelmadjid Tebboune
3               0.00         Unknown        38.9    Xavier Espot Zamora
4               3.62   Authoritarian        12.4          João Lourenço
..               ...             ...         ...                    ...
189             3.08   Authoritarian        28.4       Nguyễn Phú Trọng
190             4.39   Hybrid regime        15.4                    NaN
191             1.95   Authoritarian        14.8  Abdrabbuh Mansur Hadi
192             5.61   Hybrid regime        13.2            Edgar Lungu
193             3.16   Authoritarian        14.2     Emmerson Mnangagwa

                                        title
0                                   President
1                              Prime Minister
2                                   President
3                          Head of Government
4                                   President
..                                        ...
189  General Secretary of the Communist Party
190                                       NaN
191                                 President
192                                 President
193                                 President

[194 rows x 64 columns]>

In [3]:
print(df.describe())

         latitude   longitude  agricultural_land   forest_area     land_area  \
count  194.000000  194.000000       1.930000e+02  1.940000e+02  1.940000e+02
mean    18.975601   22.027491       2.454551e+05  2.086784e+05  6.675087e+05
std     23.876225   66.396389       6.356268e+05  7.824926e+05  1.837107e+06
min    -41.000000 -175.000000       4.000000e+00  0.000000e+00  2.027000e+00
25%      4.000000   -5.000000       6.464000e+03  3.331775e+03  2.355250e+04
50%     16.583333   21.500000       3.872780e+04  2.528925e+04  1.203750e+05
75%     40.000000   50.162500       2.150000e+05  1.236735e+05  5.237000e+05
max     65.000000  178.000000       5.285080e+06  8.153120e+06  1.637690e+07

         rural_land     urban_land  central_government_debt_pct_gdp  \
count  1.940000e+02     194.000000                       120.000000
mean   6.563711e+05    9777.116531                        66.759366
std    1.811169e+06   42301.458421                        71.806247
min    3.495450e-02       0.000000                         0.000000
25%    2.186562e+04     359.618250                        31.951300
50%    1.159945e+05    1645.170000                        55.426850
75%    4.911505e+05    4054.022500                        79.539300
max    1.622420e+07  522345.000000                       687.994000

       expense_pct_gdp           gdp  ...  net_migration  population_female  \
count       156.000000  1.930000e+02  ...     194.000000       1.940000e+02
mean         30.051403  5.144851e+11  ...     -51.407216       2.028316e+07
std          26.740880  2.307148e+12  ...   94525.968598       7.258941e+07
min           0.000267  6.034940e+07  ... -525116.000000       5.513000e+03
25%          18.371875  1.181390e+10  ...  -12242.250000       1.036218e+06
50%          27.337750  4.115390e+10  ...    -970.000000       4.502713e+06
75%          35.083500  2.519450e+11  ...    2904.250000       1.526606e+07
max         310.443000  2.546270e+13  ...  561580.000000       6.915285e+08

       population_male    population  women_parliament_seats_pct  \
count     1.940000e+02  1.940000e+02                  193.000000
mean      2.050572e+07  4.078888e+07                   25.022994
std       7.607158e+07  1.486470e+08                   12.671044
min       5.799000e+03  1.131200e+04                    0.000000
25%       1.044902e+06  2.106358e+06                   15.384600
50%       4.450049e+06  9.125614e+06                   25.252500
75%       1.478872e+07  3.031361e+07                   33.636400
max       7.311805e+08  1.417173e+09                   61.250000

       rural_population  urban_population       press  democracy_score  \
count      1.940000e+02      1.940000e+02  194.000000       194.000000
mean       1.763322e+07      2.315566e+07    2.539330         4.644536
std        7.664187e+07      7.940393e+07    1.800128         2.818297
min        0.000000e+00      5.717000e+03    0.000000         0.000000
25%        5.896640e+05      1.222244e+06    1.525000         2.722500
50%        2.512382e+06      4.508837e+06    2.400000         5.050000
75%        1.133354e+07      1.621355e+07    2.925000         6.967500
max        9.088048e+08      8.975784e+08   10.000000         9.870000

       median_age
count  194.000000
mean    25.661856
std      9.415569
min     10.500000
25%     16.950000
50%     24.950000
75%     34.050000
max     50.500000

[8 rows x 54 columns]

Which country has the maximum population

In [4]:
print(df[df['population'] == df['population'].max()]['country'])

75    India
Name: country, dtype: object

capital of the country with maximum population

In [5]:
print(df[df['population'] == df['population'].max()]['capital_city'])

75    New Delhi
Name: capital_city, dtype: object

country with least population

In [6]:
print(df[df['population'] == df['population'].min()]['country'])

179    Tuvalu
Name: country, dtype: object

In [7]:
print(df[df['population'] == df['population'].min()]['capital_city'])

179    Funafuti
Name: capital_city, dtype: object

sorting values

In [8]:
df.sort_values(by='democracy_score', ascending=False, inplace=True)

printing top 5 countries with highest democracy scores

In [9]:
print(df['country'].head())

127         Norway
74         Iceland
164         Sweden
122    New Zealand
46         Denmark
Name: country, dtype: object

In [10]:
print(df.columns)

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='object')

region wise count

In [11]:
print(df['region'].value_counts())

region
Eastern Africa               17
Western Asia                 17
Western Africa               16
Southern Europe              15
Caribbean                    13
South America                12
South-Eastern Asia           11
Middle Africa                10
Eastern Europe               10
Northern Europe              10
Western Europe                9
Southern Asia                 9
Central America               8
Northern Africa               6
Micronesia                    5
Central Asia                  5
Southern Africa               5
Eastern Asia                  5
Melanesia                     4
Polynesia                     3
Northern America              2
Australia and New Zealand     2
Name: count, dtype: int64

total region count

In [12]:
print(df['region'].value_counts().count())

22

how many countries lie in eastern europe region

In [13]:
print(df[df['region'] == 'Eastern Europe']['country'])

43      Czech Republic
151    Slovak Republic
24            Bulgaria
136             Poland
73             Hungary
139            Romania
111            Moldova
181            Ukraine
14             Belarus
140             Russia
Name: country, dtype: object

political leader of second largest population country

In [14]:
df[df['population'] == df['population'].nlargest(2).iloc[1]]['political_leader']

34    Xi Jinping
Name: political_leader, dtype: object

how many countries whose leader is unknown

In [16]:
df[df['political_leader'].isna()]['country'].count()

np.int64(7)

how many countries have republic in their full name

In [17]:
count = 0
def counting(txt):
    global count
    if 'republic' in txt.lower():
        count+= 1
    return txt
df['country_long'] = df['country_long'].apply(counting)
print(count)

125

country in africa which has highest population

In [18]:
africa_df = df[df['continent'] == 'Africa']
africa_df[africa_df['population'] == africa_df['population'].max()]['country']

125    Nigeria
Name: country, dtype: object